apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureAllowedUsersGroups
metadata:
  name: psp-allowed-users-groups
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    runAsUser: {{ .Values.runAsUser }}
