apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: ${identity_id}
    azure.workload.identity/tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0