apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: humio
spec:
  selector:
    matchLabels:
      app: humio
  serviceName: "humio"
  replicas: 1
  template:
    metadata:
      labels:
        app: humio
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: humio
        image: humio/humio
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 9200
          name: ingest
        volumeMounts:
        - name: humio-disk
          mountPath: /data
        env:
        - name: AUTHENTICATION_METHOD
          value: "single-user"
        - name: SINGLE_USER_PASSWORD
          value: "{{ .Values.singleUserPassword }}"
        - name: ELASTIC_PORT
          value: "9200"
      resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: humio-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: managed-premium-retain
      resources:
        requests:
          storage: 100Gi
