apiVersion: v1
kind: ServiceAccount
metadata:
  name: "radix-monitoring"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "radix-monitoring"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "radix-monitoring"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["radix.equinor.com"]
  resources: ["radixapplications", "radixdeployments"]
  verbs: ["*"]

- apiGroups: ["radix.equinor.com"]
  resources: ["radixregistrations"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create"]
  
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]