kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: radixregistration-reader
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["radixregistration"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: radix-operator
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radixregistration-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-radix-operator
    namespace: {{ .Release.Namespace }} 