{{- if .Values.clusterWildcardCert.enabled -}}
# Add wildcard tls cert by
# 1. Create the secret to hold tls cert
# 2. Create the Credential that cert-manager will use to provision the cert and store in the same secret as in step 1.
#
# The Certificate object does not allow us to add annotiations to the secret it will create.
# And we need to annotate it to enable kubed to sync it.
# The workaround is to manually create the secret along with the annotation we need.
# Cert-manager will then simply update it when ready.
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  annotations:
    kubed.appscode.com/sync: "sync=cluster-wildcard-tls-cert"
  name: cluster-wildcard-tls-cert
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cluster-wildcard-tls-cert
spec:
  secretName: cluster-wildcard-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: "*.{{ .Values.clusterWildcardCert.deploymentTargetName }}.{{ .Values.clusterWildcardCert.environment }}.radix.equinor.com"
  dnsNames:
  - "{{ .Values.clusterWildcardCert.deploymentTargetName }}.{{ .Values.clusterWildcardCert.environment }}.radix.equinor.com"
  acme:
    config:
    - dns01:
        provider: azure-dns
      domains:
      - "*.{{ .Values.clusterWildcardCert.deploymentTargetName }}.{{ .Values.clusterWildcardCert.environment }}.radix.equinor.com"
      - "{{ .Values.clusterWildcardCert.deploymentTargetName }}.{{ .Values.clusterWildcardCert.environment }}.radix.equinor.com"
{{- end -}}