{{if .Values.externalDns.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "external-dns"
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "external-dns"
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "external-dns-viewer"
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-external-dns"
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:{{ .Values.externalDns.imageTag }}
        args:
        - --source=service
        - --source=ingress
        - --interval=10s
        - --domain-filter={{ .Values.externalDns.environment }}.radix.equinor.com # This is really a zone filter (value should be the zone name).
        - --registry=txt
        - --txt-owner-id={{ .Values.externalDns.clusterName }} # Some unique value, this will appear as owner in the dns txt record.
        - --provider=azure
        - --azure-resource-group=radix-common-{{ .Values.externalDns.environment }} # The resource group where the dns zone resides.
        volumeMounts:
        - name: external-dns-secret # payload must be "azure.json"
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: external-dns-secret
        secret:
          secretName: {{ .Release.Name }}-external-dns-secret
---

apiVersion: v1
kind: Secret
metadata:  
  name: {{ .Release.Name }}-external-dns-secret
  labels:
    app: "radix-platform"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  azure.json: {{ template "external-dns-secret" . }}

{{end}}