apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret-envs
type: Opaque
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.grafana.oAuthClientSecret }}
  GF_DATABASE_PASSWORD: {{ .Values.grafana.mysqlDBPassword }}
