# AKS cluster deploy pipeline

parameters:
- name: source_cluster
  displayName: Source Cluster
  type: string

- name: destination_cluster
  displayName: Destination Cluster
  type: string

- name: user_prompt
  displayName: User prompt
  type: string
  default: false
  values:
  - true
  - false

- name: move_ingresses
  displayName: Move Ingresses
  type: string
  default: false
  values:
  - true
  - false

- name: pipeline_run
  displayName: Pipeline Run
  type: string
  default: true
  values:
  - true
  - false

- name: radix_container_logs
  displayName: Radix container logs
  type: string
  default: false
  values:
  - radix-container-logs-dev
  - radix-container-logs-playground
  - radix-container-logs-prod
  - false

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployNewCluster
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ServiceConnectionAzureDevOpsRadixDev'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
              ls
              cd scripts
              ls
      env:
        SOURCE_CLUSTER: ${{ parameters.source_cluster }}
        DEST_CLUSTER: ${{ parameters.destination_cluster }}
        USER_PROMPT: ${{ parameters.user_prompt }}
        MOVE_INGRESSES: ${{ parameters.move_ingresses }}
        PIPELINE_RUN: ${{ parameters.pipeline_run }}
        SPOID: $(SPOID)
#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'RADIX_ZONE_ENV=./radix-zone/radix_zone_dev.env SOURCE_CLUSTER=weekly-26 DEST_CLUSTER=weekly-26- USER_PROMPT=false ./migrate.sh'