apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-platform
spec:
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
    - name: test
      build:
        from: main
  components:
    - name: public-site
      src: "./public-site"
      ports:
        - name: http
          port: 8080
      public: true
      environmentConfig:
        - environment: prod
          replicas: 2
          resources:
            requests:
              memory: "10Mi"
              cpu: "5m"
            limits:
              memory: "20Mi"
              cpu: "10m"
