apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-platform
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: AddDocumentationForDeployOnly
      build:
        from: RA-1201-AddDocumentationForDeployOnly
  components:
    - name: public-site
      src: "./public-site"
      ports:
       - name: http
         port: 80
      public: true
      environmentConfig:
      - environment: prod
        resources:
          requests:
            memory: "10Mi"
            cpu: "5m"
          limits:
            memory: "20Mi"
            cpu: "10m"
