---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: active-cluster-wildcard-tls-cert
spec:
  secretName: active-cluster-wildcard-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "*.$AZ_RESOURCE_DNS"
  dnsNames:
  - "*.$AZ_RESOURCE_DNS"
  - "$AZ_RESOURCE_DNS"
