---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: active-cluster-wildcard-tls-cert
spec:
  secretName: active-cluster-wildcard-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "*.$AZ_RESOURCE_DNS"
  dnsNames:
  - "*.$AZ_RESOURCE_DNS"
  - "$AZ_RESOURCE_DNS"
