---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app-wildcard-tls-cert
spec:
  secretName: app-wildcard-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "*.app.$AZ_RESOURCE_DNS"
  dnsNames:
  - "*.app.$AZ_RESOURCE_DNS"
  - "app.$AZ_RESOURCE_DNS"
