---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ${CERT_ISSUER}
spec:
  acme:
    # The ACME server URL
    server: ${ACME_URL}
    # Email address used for ACME registration.
    # Let's Encrypt will use this to contact you about expiring certificates and issues related to your account.
    email: Radix@StatoilSRM.onmicrosoft.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${CERT_ISSUER}
    # HTTP challenge is not supported for wildcard certificates
    # http01: {}
    solvers:
      - dns01:
          azuredns:
            clientID: "${DNS_SP_ID}" # The appId of the dns service principal which can access the az dns zone in the environment (prod, dev, ...) where the cluster is hosted. Ex: az ad sp show --id http://radix-dns-dev --query appId
            clientSecretSecretRef:
              key: client-secret
              name: cert-manager-credentials-dns
            subscriptionID: "${AZ_SUBSCRIPTION_ID}" # The id of the subscription that controls the az dns zone. Ex: az account show -s "Omnia Radix Development" --query id
            tenantID: "${DNS_SP_TENANT_ID}" # The id of the tenant which host the dns service principal. Ex: az ad sp show --id http://radix-dns-dev --query appOwnerTenantId
            resourceGroupName: "${AZ_RESOURCE_GROUP_COMMON}"
            hostedZoneName: "${AZ_RESOURCE_DNS}"
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud
            
---

apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-credentials-dns
  namespace: cert-manager
type: Opaque
data:
  client-secret: ${DNS_SP_PASSWORD_base64} # base64 encode of Azure AD password
