trigger:
  branches:
    include:
      - devops-workitem-automation

pr: none
variables:
  System.Debug: true

stages:
  - stage: dev
    jobs:
      - job: checkversion
        pool:
          VmImage: ubuntu-latest
        steps:
        - script: az extension add -n azure-devops
          displayName: 'Install Azure DevOps Extension'

        - script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
          env:
            AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
          displayName: 'Login Azure DevOps Extension'

        - script: az devops configure --defaults organization=https://dev.azure.com/Equinor project=Radix --use-git-aliases true
          displayName: 'Set default Azure DevOps organization and project'

        - script: az boards work-item show --id 48996
          displayName: 'testing az devops'

        - task: AzurePowerShell@5
          env:
            clientId: $(CLIENTID)
            clientSecret: $(CLIENTSECRET)
          inputs:
            ScriptType: InlineScript
            azureSubscription: 'Azure - Dev'
            azurePowerShellVersion: LatestVersion
            pwsh: true
            Inline: |
              az login --service-principal --username "$Env:clientId" --password "$Env:clientSecret" --tenant ${env:TENANT}
              get-azcontext
              az devops configure -l
              kubectl
              helm version
              Import-Module .\powershell-modules\Check-Helm\Check-Helm.psm1
              Write-Host "Starting version check in dev cluster..."
              .\scripts\devops\check-component-version.ps1 -RadixEnvironment ".\scripts\radix-zone\radix_zone_dev.json"
              Write-Host "Starting version check in playground cluster..."
              .\scripts\devops\check-component-version.ps1 -RadixEnvironment ".\scripts\radix-zone\radix_zone_playground.json"