# cert-manger child chart
cert-manager:
  enabled: true

  # cert-manager chart values:
  ingressShim:
    defaultIssuerName: letsencrypt-prod
    defaultIssuerKind: ClusterIssuer
    defaultACMEChallengeType: dns01
    defaultACMEDNS01ChallengeProvider: azure-dns