---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  annotations:
    # recommended to use namespaced identites https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/
    aadpodidentity.k8s.io/Behavior: namespaced 
  name: certman-identity
  namespace: cert-manager # change to your preferred namespace
spec:
  type: 0 # MSI
  resourceID: ${RESOURCE_ID} # Resource Id From Previous step
  clientID: ${CLIENT_ID} # Client Id from previous step
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: certman-id-binding
  namespace: cert-manager # change to your preferred namespace
spec:
  azureIdentity: certman-identity
  selector: certman-label # This is the label that needs to be set on cert-manager pods
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${CERT_ISSUER}
spec:
  acme:
    # The ACME server URL
    server: ${ACME_URL}
    # Email address used for ACME registration.
    # Let's Encrypt will use this to contact you about expiring certificates and issues related to your account.
    email: Radix@StatoilSRM.onmicrosoft.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${CERT_ISSUER}
    # HTTP challenge is not supported for wildcard certificates
    # http01: {}
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: "${AZ_SUBSCRIPTION_ID}" # The id of the subscription that controls the az dns zone. Ex: az account show -s "Omnia Radix Development" --query id
          resourceGroupName: "${AZ_RESOURCE_GROUP_COMMON}"
          hostedZoneName: "${AZ_RESOURCE_DNS}"
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud