environment: "d1" # template
flux_folder: "d1" # template
cluster_type: "production"
subscription_shortname: "s612" # template
location: "northeurope" # template
secondary_location: "westeurope" # template
developers: ["bed2b667-ceec-4377-83f7-46888ed23887"] # AZ PIM OMNIA RADIX Cluster Admin
testzone: true # template
zoneconfig:
  RADIX_API_REQUIRE_APP_CONFIGURATION_ITEM: "true"
  RADIX_API_REQUIRE_APP_AD_GROUPS: "true"
  APP_REGISTRATION_NETWORKPOLICY_CANARY: "ar-radix-networkpolicy-canary"
backend:
  resource_group_name: "s612-tfstate" # template
  storage_account_name: "s612radixinfra" # template
  container_name: "infrastructure"
  subscription_id: "939950ec-da7e-4349-8b8d-77d9c278af04" # template
  tenant_id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0" # template
  terraform_storage_id: "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/s612-tfstate/providers/Microsoft.Storage/storageAccounts/s612radixinfra" # template
networksets:
  networkset1:
    vnet: "10.8.0.0"
    ingressIP: "23.101.60.142"
    egress:
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-001"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-002"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-003"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-004"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-005"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-006"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-007"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-008"
  networkset2:
    vnet: "10.9.0.0"
    ingressIP: "23.101.60.136"
    egress:
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-009"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-010"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-011"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-012"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-013"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-014"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-015"
      - "/subscriptions/939950ec-da7e-4349-8b8d-77d9c278af04/resourceGroups/clusters-d1/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-d1-northeurope-016"
clusters:
  disaster-22:
    aksversion: "1.31.8"
    networkset: "networkset1"
    network_policy: "cilium"
