environment: "extmon"
subscription_shortname: "s940"
location: "northeurope"
developers: "bed2b667-ceec-4377-83f7-46888ed23887" # AZ PIM OMNIA RADIX Cluster Admin - dev
backend:
  resource_group_name: = "s940-tfstate"
  storage_account_name: = "s940radixinfra"
  container_name: "infrastructure"
  subscription_id: "ded7ca41-37c8-4085-862f-b11d21ab341a"
  tenant_id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  ip_key_vault_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/common-platform/providers/Microsoft.KeyVault/vaults/radix-keyv-platform"
  terraform_storage_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/s940-tfstate/providers/Microsoft.Storage/storageAccounts/s940radixinfra"
networksets:
  networkset1:
    vnet: "10.3.0.0"
    ingressIP: "40.112.68.27"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-extmon/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-extmon-northeurope-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-extmon/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-extmon-northeurope-004"
  networkset2:
    vnet: "10.4.0.0"
    ingressIP: "40.112.68.26"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-extmon/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-extmon-northeurope-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-extmon/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-extmon-northeurope-003"
clusters:
  ext-mon-11:
    aksversion: "1.29.2"
    networkset: "networkset2"
    network_policy: "calico"
