environment: "c2"
subscription_shortname: "s940"
location: "westeurope"
developers: "be5526de-1b7d-4389-b1ab-a36a99ef5cc5" # Radix Platform Operators
backend:
  resource_group_name:   "s940-tfstate"
  storage_account_name:  "s940radixinfra"
  container_name:        "infrastructure"
  subscription_id:       "ded7ca41-37c8-4085-862f-b11d21ab341a"
  tenant_id:             "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  ip_key_vault_id:       "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/common-c2/providers/Microsoft.KeyVault/vaults/radix-keyv-c2"
  terraform_storage_id:  "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/s940-tfstate/providers/Microsoft.Storage/storageAccounts/s940radixinfra"
clusters: 
  c2-11:
    aksversion: "1.29.2"
    networkset: "clusterset1"
    network_policy: "calico"
    dns_prefix: ""
