environment: "c2"
subscription_shortname: "s940"
location: "westeurope"
developers: ["0e0d22c6-9f03-48a5-89be-be7b060c8a32"] # AZ PIM OMNIA RADIX Cluster Admin - prod
backend:
  resource_group_name: "s940-tfstate"
  storage_account_name: "s940radixinfra"
  container_name: "infrastructure"
  subscription_id: "ded7ca41-37c8-4085-862f-b11d21ab341a"
  tenant_id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  ip_key_vault_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/common-c2/providers/Microsoft.KeyVault/vaults/radix-keyv-c2"
  terraform_storage_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/s940-tfstate/providers/Microsoft.Storage/storageAccounts/s940radixinfra"
networksets:
  networkset1:
    vnet: "10.5.0.0"
    ingressIP: "20.61.119.160"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c2-prod-008"
  networkset2:
    vnet: "10.6.0.0"
    ingressIP: "20.61.119.161"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-008"
  networkset3:
    vnet: "10.7.0.0"
    ingressIP: "20.61.119.162"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-009"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-0010"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-011"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-012"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-013"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-014"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-015"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c2/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c2-westeurope-016"
clusters:
  c2-11:
    aksversion: "1.30.9"
    networkset: "networkset1"
    network_policy: "calico"
