#!/usr/bin/env bash

CLUSTER_LOCATION="./terraform/clusters/${ENVIRONMENT}"
TARGET_LOCATION=$(find "${CLUSTER_LOCATION}" -name "${TARGET_NAME}")
DESTINATION_LOCATION="${CLUSTER_LOCATION}/${MIGRATION_STRATEGY}/${DESTINATION_NAME}"

cp $ARGS "${TARGET_LOCATION}" "${DESTINATION_LOCATION}"
