#!/usr/bin/env bash

CLUSTER_LOCATION="./terraform/clusters"
TARGET_LOCATION=$(find "${CLUSTER_LOCATION}" -name "${SOURCE_CLUSTER}")
DESTINATION_LOCATION="${CLUSTER_LOCATION}/${SUBSCRIPTION}/${ENVIRONMENT}/${MIGRATION_STRATEGY}/${DEST_CLUSTER}"

cp $ARGS "${TARGET_LOCATION}" "${DESTINATION_LOCATION}"
