apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-backup-uploader
  namespace: monitor
  annotations:
    azure.workload.identity/client-id: "${RADIX_ID_PROMETHEUS_BACKUP_MI_CLIENT_ID}"
