apiVersion: v1
name: radix-e2e-monitoring
version: 1.0.5
appVersion: 1.0.5
kubeVersion: ">=1.11.2"
description: K6 continous performance tests
keywords:
  - radix
home: radix.equinor.com
sources:
  - https://github.com/equinor/radix-platform
maintainers: 
  - name: Stian Ovrevage
    email: sov@equinor.com
deprecated: false