apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx

    {{- if .Values.enableAutoTLS }}
    kubernetes.io/tls-acme: "true"
    {{- end }}

  labels:
    radix-app: {{ .Values.application }}
    radix-component: {{ .Values.component }}
  name: {{ .Values.component }}.custom-domain
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.aliasUrl }}
      http:
        paths:
        - backend:
            serviceName: {{ .Values.component }}
            servicePort: {{ .Values.componentPort }}
          path: /
  tls:
    - hosts:
      - {{ .Values.aliasUrl }}
      secretName: {{ .Values.aliasUrl }}
