apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: radix-cicd-canary
  name: deployment-scaler
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]