apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler
  namespace: radix-cicd-canary
subjects:
- kind: User
  name: xx
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io