environment: "${destinationzone}" # template
flux_folder: "${destinationzone}" # template
cluster_type: "production"
subscription_shortname: "${subscription_shortname}" # template
location: "${location}" # template
developers: ["0e0d22c6-9f03-48a5-89be-be7b060c8a32"] # AZ PIM OMNIA RADIX Cluster Admin - prod
zoneconfig:
  RADIX_API_REQUIRE_APP_CONFIGURATION_ITEM: "true"
  RADIX_API_REQUIRE_APP_AD_GROUPS: "true"
  APP_REGISTRATION_NETWORKPOLICY_CANARY: "ar-radix-networkpolicy-canary"
  secondary_location: "${secondary_location}"
backend:
  resource_group_name: "${subscription_shortname}-tfstate" # template
  storage_account_name: "${subscription_shortname}radixinfra" # template
  container_name: "infrastructure"
  subscription_id: "${subscription_id}" # template
  tenant_id: "${tenant_id}" # template
  terraform_storage_id: "/subscriptions/${subscription_id}/resourceGroups/${subscription_shortname}-tfstate/providers/Microsoft.Storage/storageAccounts/${subscription_shortname}radixinfra" # template
networksets:
  networkset1:
    vnet: "10.11.0.0"
    ingressIP: "94.245.89.217"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-008"
  networkset2:
    vnet: "10.12.0.0"
    ingressIP: "94.245.89.220"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-009"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-010"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-011"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-012"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-013"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-014"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-015"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-northeurope-016"
clusters:
  c3-20:
    aksversion: "1.32.3"
    networkset: "networkset1"
    network_policy: "cilium"
    activecluster: true
