apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cert-manager-webhook-webhook-tls
data:
  tls.crt: ""
  tls.key: ""

---

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cert-manager-webhook-ca
data:
  tls.crt: ""
  tls.key: ""