grafana:
  enabled: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: "0m" # Added to a default of 100m
        memory: "0Mi" # Added to a default of 25Mi

prometheusOperator:
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: "0m" # Added to a default of 200m
        memory: "950Mi" # Added to a default of 50m
    retention: 30d
    serviceMonitorNamespaceSelector:
      any: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium-retain-nocache
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 120Gi
        selector: {}
