environment: "dev"
subscription_shortname: "s941"
location: "northeurope"
backend:
  resource_group_name:   "s941-tfstate"
  storage_account_name:  "s941radixinfra"
  container_name:        "infrastructure"
  subscription_id:       "16ede44b-1f74-40a5-b428-46cca9a5741b"
  tenant_id:             "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
