apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    # Uncomment and adjust this value this if there are multiple separate prometheus servers in the cluster
    # prometheus: <cluster-name>-<env>-prometheus (For example: playground-v1-5-0-test-dev-prometheus)
