{{- if .Values.createIngressServiceMonitor -}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-nginx-ingress"
  labels:
    prometheus: kube-prometheus
    app: radix-platform
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  endpoints:
  - interval: 5s
    port: metrics
  jobLabel: nginx-ingress
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: nginx-ingress

{{- end -}}
