apiVersion: radix.equinor.com/v1
kind: RadixJob
metadata:
  annotations:
    radix-branch: {{ .Values.cloneBranch }}
  labels:
    radix-app: {{ .Values.name }}
  name: {{ .Values.name }}-{{ .Values.cloneBranch }}-init-deploy-{{ .Values.imageTag }}
  namespace: {{ .Values.name }}-app
spec:
  appName: {{ .Values.name }}
  build:
    branch: {{ .Values.cloneBranch }}
    commitID: ""
    imageTag: {{ .Values.imageTag }}
    pushImage: true
    radixFileName: /workspace/radixconfig.yaml
  cloneURL: {{ .Values.cloneURL }}
  dockerRegistry: {{ .Values.containerRegistry }}
  pipeLineType: build-deploy
  pipelineImage: {{ .Values.pipelineImageTag }}