name: AKS Apply
on:
  workflow_dispatch:
permissions: {}
jobs:
  terraform-apply:
    name: Terraform apply
    runs-on: radix-runner
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: "dev"
            subscription: "s941"
          - name: "playground"
            subscription: "s941"
          # - name: "platform"
          #   subscription: "s940"
          # - name: "c2"
          #   subscription: "s940"
    environment: ${{matrix.target.name }}
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '2'
      - name: 'Az login'
        if: ${{ github.ref == 'refs/heads/master' && inputs.terraformapply }}
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        if: ${{ github.ref == 'refs/heads/master' && inputs.terraformapply }}
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 'latest'
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/master' && inputs.terraformapply }}
        id: apply
        env:
          ARM_USE_OIDC: true
          ARM_USE_AZUREAD: true
        run: |
          terraform -chdir="./terraform/subscriptions/${{ matrix.target.subscription }}/${{ matrix.target.name }}/pre-clusters" init
          terraform -chdir="./terraform/subscriptions/${{ matrix.target.subscription }}/${{ matrix.target.name }}/pre-clusters" apply -auto-approve
          terraform -chdir="./terraform/subscriptions/${{ matrix.target.subscription }}/${{ matrix.target.name }}/pre-clusters" apply -auto-approve

