name: AzureAuditLogs

on:
  push:
    branches:
      - master
      - RA-1256auditLog
  paths:
    - '.github/workflows/sqlLogStorageAccounts.yml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/sqlLogStorageAccounts.yml'

env:
  # Prod
  prodSubscriptionId: 'ded7ca41-37c8-4085-862f-b11d21ab341a'

  # Dev
  devSubscriptionId: '16ede44b-1f74-40a5-b428-46cca9a5741b'

  # Shared
  settingName: azureauditlog
  auditLogStorageName: radixazauditlogs

jobs:
############## DEV STAGE ##############

  dev:
    runs-on: ubuntu-latest
    env:
        envName: dev
        devRgName: rg-radix-shared-dev
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Set dynamic variables for the job
    - name: Set job variables
      shell: pwsh
      run: |

        # Set timestamp variable for jobs
        $currentTime = (get-date).ToString("dd-MM-yyyyThhMMZ")
        Write-Output "::set-env name=timestamp::$currentTime"

    # Install powershell modules
    - name: Install powershell modules
      shell: pwsh
      run: |
        
        Install-Module az.resources -force
        Install-Module az.storage -force

    # Azure login for powershell
    - name: Azure login
      shell: pwsh
      run: |
        $azureAplicationId = "${{ secrets.DEV_AZURE_CREDENTIALS_CLIENT_ID }}"
        $azureTenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $azurePassword = ConvertTo-SecureString "${{ secrets.DEV_AZURE_CREDENTIALS_CLIENT_SECRET }}" -AsPlainText -Force
        $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
        Add-azAccount -Credential $psCred -TenantId $azureTenantId -ServicePrincipal


    # Set subsctiption to develop and verify
    - name: Set Azure subscription
      shell: pwsh
      run: |
      
        Set-AzContext -SubscriptionId "${{ env.devSubscriptionId }}"
        
        $subscription = (Get-AzContext)
        if ($subscription.Subscription.Id -eq "${{ env.devSubscriptionId }}") {
          Write-Output "Using subscription $($subscription.subscription.Name)"
          exit 0
          
        }
        else {
          Write-Output "Subscription does not match. Terminating script"
          exit 1
        }

    # Create storage account for Azure audit logs
    - name: Storage Account for Azure Subscription Audit logs
      shell: pwsh
      run: |

        # Set task variables
        $rg = "${{ env.devRgName }}"
        $templateFile = "$env:GITHUB_WORKSPACE/arm-templates/azureAuditLogStorageAccount.json"
        $storeAccountName = "${{ env.auditLogStorageName }}${{ env.envName }}"

        # Deploy Storage Account for Audit logs
        New-AzResourceGroupDeployment `
          -Name "sql-log-${{ env.timestamp }}" `
          -ResourceGroupName $rg `
          -TemplateFile $templateFile `
          -storageAccountName $storeAccountName `
          -accountType Standard_LRS `
          -kind StorageV2 `
          -accessTier cool


    # Enable auditlog for dev subsciption
    - name: Enable auditlog for dev subsciption
      shell: pwsh
      run: |

        # Set variables
        $rg = "${{ env.devRgName }}"
        $templateFile = "$env:GITHUB_WORKSPACE/arm-templates/auditlogs.json"
        $storeAccountName = "${{ env.auditLogStorageName }}${{ env.envName }}"
        $storageAccountId = (Get-AzStorageAccount -ResourceGroupName $rg -StorageAccountName $storeAccountName).Id

        # Deploy the ARM template
        New-AzDeployment `
          -Name "auditlog-${{ env.timestamp }}" `
          -Location "norwayeast" `
          -TemplateFile $templateFile `
          -settingName ${{ env.settingName }} `
          -storageAccountId "$storageAccountId"

    # Azure logout 
    - name: logout
      shell: pwsh
      run: |
        Logout-azAccount


############## PROD STAGE ##############

  prod:
    needs: dev
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
        envName: prod
        devRgName: rg-radix-prod-dev
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Set dynamic variables for the job
    - name: Set job variables
      shell: pwsh
      run: |

        # Set timestamp variable for jobs
        $currentTime = (get-date).ToString("dd-MM-yyyyThhMMZ")
        Write-Output "::set-env name=timestamp::$currentTime"

    # Install powershell modules
    - name: Install powershell modules
      shell: pwsh
      run: |
        
        Install-Module az.resources -force
        Install-Module az.storage -force

    # Azure login for powershell
    - name: Azure login
      shell: pwsh
      run: |
        $azureAplicationId = "${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_ID }}"
        $azureTenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $azurePassword = ConvertTo-SecureString "${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_SECRET }}" -AsPlainText -Force
        $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
        Add-azAccount -Credential $psCred -TenantId $azureTenantId -ServicePrincipal

    # Set subsctiption to develop and verify
    - name: Set Azure subscription
      shell: pwsh
      run: |
      
        Set-AzContext -SubscriptionId "${{ env.prodSubscriptionId }}"
        
        $subscription = (Get-AzContext)
        if ($subscription.Subscription.Id -eq "${{ env.prodSubscriptionId }}") {
          Write-Output "Using subscription $($subscription.subscription.Name)"
          exit 0
          
        }
        else {
          Write-Output "Subscription does not match. Terminating script"
          exit 1
        }


    # Create storage account for Azure audit logs
    - name: Storage Account for Azure Subscription Audit logs
      shell: pwsh
      run: |

        # Set task variables
        $rg = "${{ env.prodRgName }}"
        $templateFile = "$env:GITHUB_WORKSPACE/arm-templates/azureAuditLogStorageAccount.json"
        $storeAccountName = "${{ env.auditLogStorageName }}${{ env.envName }}"

        # Deploy Storage Account for Audit logs
        New-AzResourceGroupDeployment `
          -Name "sql-log-${{ env.timestamp }}" `
          -ResourceGroupName $rg `
          -TemplateFile $templateFile `
          -storageAccountName $storeAccountName `
          -accountType Standard_LRS `
          -kind StorageV2 `
          -accessTier cool


    # Enable auditlog for prod subsciption
    - name: Enable auditlog for prod subsciption
      shell: pwsh
      run: |

        Set-AzContext -SubscriptionId "${{ env.prodSubscriptionId }}"
        
        $subscription = (Get-AzContext)
        if ($subscription.Subscription.Id -eq "${{ env.prodSubscriptionId }}") {
          Write-Output "Using subscription $($subscription.subscription.Name)"
          exit 0
          
        }
        else {
          Write-Output "Subscription does not match. Terminating script"
          exit 1
        }


    # Create storage account and SQL logs
    - name: Storage Account for SQL logs
      shell: pwsh
      run: |


    # Azure logout 
    - name: logout
      shell: pwsh
      run: |
        Logout-azAccount