name: Check Terraform infrastructure
on:
  pull_request:
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Subscription'
        type: choice
        required: true
        options:
          - 's941'
        default: 's941'
      
      terraformapply:
        description: 'Terraform apply'
        type: boolean
        required: true
        default: false


    # secrets:
    #   AZURE_CLIENT_ID:
    #     description: The client ID of the Azure AD service principal to use for authenticating to Azure.
    #     required: true

    #   AZURE_SUBSCRIPTION_ID:
    #     description: The ID of the Azure subscription to create the resources in.
    #     required: true

    #   AZURE_TENANT_ID:
    #     description: The ID of the Azure tenant to create the resources in.
    #     required: true
  

jobs:
  terrform-dev:
    name: Check infrastructure consistency in s941
    runs-on: ubuntu-latest
    environment: s941
    env:
      subscription: s941
      terraform_version: ~1.3.0
    strategy:
      matrix:
        enviroment: [dev, playground]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get GitHub Public IP
        id: github_public_ip
        uses: haythem/public-ip@v1.3

      - name: Add GitHub IP to StorageAccount
        run: |
          az storage account network-rule add \
            --resource-group "${{ env.subscription }}-tfstate" \
            --account-name "${{ env.subscription }}radixinfra" \
            --ip-address ${{ steps.github_public_ip.outputs.ipv4 }} >/dev/null

      - name: Lets sleep for 30 seconds for FW rule to complete
        run: sleep 30s

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Check terrorm in ${{ matrix.enviroment }}
        working-directory: terraform/subscriptions/${{ env.subscription }}
        run: ./summary-${{ matrix.enviroment }}.sh   
      
      - name: Revoke GitHub IP on StorageAccount
        run: |
          az storage account network-rule remove \
            --resource-group "s941-tfstate" \
            --account-name "s941radixinfra" \
            --ip-address ${{ steps.github_public_ip.outputs.ipv4 }} >/dev/null
