name: clusters
on:
  push:
    branches:
      - master
    # paths:
    #   - '.github/workflows/sqlLogStorageAccounts.yml'

# permissions:
#   id-token: write
#   contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    # Queue jobs that target the same Terraform configuration.
    concurrency:
      group: terraform @ terraform/clusters/dev/sondre-dev
      cancel-in-progress: false

    # Set permissions required to login to Azure using OIDC.
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: terraform/clusters/dev/sondre-dev

    # Configure OIDC authentication to Azure using environment variables.
    # Required by the AzureRM backend and provider.
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.3.4

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config=backend_config.env

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule'
        run: terraform apply -auto-approve