name: List files
on:
  push:
    branches:
      - master
    paths:
      - 'terraform/clusters/**'
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    paths:
      - 'terraform/clusters/**'
jobs:
  Get_radix_environment:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.event_name == 'push'
    name: Get radix environment
    runs-on: ubuntu-latest
    outputs:
      radix_environment: ${{ steps.set-matrix.outputs.radix_environment }}
    env:
      path: terraform/clusters
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "radix_environment=$(ls ${{ env.path }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  List_files:
    needs: Get_radix_environment
    name: List files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        radix_environment: ${{ fromJson(needs.Get_radix_environment.outputs.radix_environment) }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.convertedArr }}
    env:
      path: terraform/clusters/${{ matrix.radix_environment }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          cd ${{ env.path }}
          mapfile -t migration_strategies < <(ls .)

          migration_strategy_tmp=$(for migration_strategy in "${migration_strategies[@]}"; do
              if [[ -z $(ls "$migration_strategy") ]]; then continue; fi
              mapfile -t cluster_names < <(ls "$migration_strategy")
              for cluster_name in "${cluster_names[@]}"; do
                jq -n \
                  --arg migration_strategy "$migration_strategy" \
                  --arg cluster_name "$cluster_name" \
                  '{migration_strategy:$migration_strategy, cluster_name:$cluster_name}'; 
              done
            done)
          migration_strategy=$(echo "${migration_strategy_tmp}" | jq -s .) 

          echo "$migration_strategy"
          echo "convertedArr=$(echo "$migration_strategy" | jq -c)" >> $GITHUB_OUTPUT

  Terraform:
    needs: [List_files, Get_radix_environment]
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    strategy:
      fail-fast: false
      matrix:
        cluster_info: ${{ fromJSON(needs.List_files.outputs.matrix) }}
        radix_environment: ${{ fromJson(needs.Get_radix_environment.outputs.radix_environment) }}
    with:
      cluster_name: ${{ matrix.cluster_name }}
      environment: operations
      radix_environment: ${{ matrix.radix_environment }}
      terraform_version: ~1.3.0
      working_directory: terraform/clusters/${{ matrix.radix_environment }}/${{ matrix.cluster_info.migration_strategy }}/${{ matrix.cluster_info.cluster_name }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
