name: lock-resources
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read
jobs:
  lock-clusters:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: "platform"
            zoneFile: "prod"
            subscription: "s940"
            client_id: "5b6da3d2-84f9-4703-b253-f6b7a528b080"
          - name: "c2"
            zoneFile: "c2"
            subscription: "s940"
            client_id: "fa0fa160-648d-46f0-93ce-65fe0838a075"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: 'Az login'
        uses: azure/login@v2
        with:
          client-id: ${{ matrix.target.client_id }}
          tenant-id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
          subscription-id: "ded7ca41-37c8-4085-862f-b11d21ab341a"

      - name: Get GitHub Public IP
        id: github_public_ip
        run: echo "ipv4=$(curl 'https://ifconfig.me/ip')" >> $GITHUB_OUTPUT

      - name: Add GitHub IP to StorageAccount
        run: |
          az storage account network-rule add \
            --resource-group "s940-tfstate" \
            --account-name "s940radixinfra" \
            --ip-address ${{ steps.github_public_ip.outputs.ipv4 }} >/dev/null

      - name: Lets sleep for 30 seconds for FW rule to complete
        run: sleep 30s

      - name: Setup Terraform
        id: update_firewall
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'

      - name: lock-resources
        run: RADIX_ZONE=${{matrix.target.zoneFile}} SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK }} .github/workflows/scripts/check_resource_lock.sh

      - name: Revoke GitHub IP on StorageAccount
        if: ${{ steps.update_firewall.outcome == 'success' && !cancelled()}} # Always run this step even if previous step failed
        run: |
          az storage account network-rule remove \
            --resource-group "s940-tfstate" \
            --account-name "s940radixinfra" \
            --ip-address ${{ steps.github_public_ip.outputs.ipv4 }} >/dev/null
