name: Migrate cluster
on:
  workflow_dispatch:
    inputs:

      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
          - "s940"
          - "s941"
        default: s941

      environment:
        description: "Cluster environment"
        required: true
        type: choice
        options:
          - "dev"
          - "playground"
          - "prod"
          - "c2"

      migration_strategy:
        description: "migration strategy"
        required: true
        type: choice
        options:
          - "at"
          - "aa"
        default: at

      source_cluster:
        description: "Source cluster"
        required: true
        type: string
        default: weekly-01

      dest_cluster:
        description: "Destination cluster"
        required: true
        type: string
        default: weekly-02

jobs:
  Migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy cluster
        run: |
          ARGS="-r" \
          ENVIRONMENT="${{ inputs.environment }}" \
          MIGRATION_STRATEGY="${{ inputs.migration_strategy }}" \
          SUBSCRIPTION="${{ inputs.subscription }}" \
          SOURCE_CLUSTER="${{ inputs.source_cluster }}" \
          DEST_CLUSTER="${{ inputs.dest_cluster }}" \
          .github/workflows/scripts/copy.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: equinor/omnia-radix
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            **${{ github.workflow }}:**

            SOURCE_CLUSTER: ${{ inputs.source_cluster }}
            DEST_CLUSTER: ${{ inputs.dest_cluster }}

            Label/Relabel PR with `deploy` to start terraform planning actions.

            `Merge pull request` to apply terraform.
          branch: migrate_${{ inputs.source_cluster }}_${{ inputs.dest_cluster }}
          commit-message: "[Migrate] SOURCE_CLUSTER: ${{ inputs.source_cluster }}, DEST_CLUSTER: ${{ inputs.dest_cluster }}"
          committer: GitHub <noreply@github.com>
          delete-branch: true
          labels: |
            ${{ inputs.environment }}
          reviewers: equinor/omnia-radix
          title: '[Migrate] SOURCE_CLUSTER: ${{ inputs.source_cluster }}, DEST_CLUSTER: ${{ inputs.dest_cluster }}'
          token: ${{ github.token }}
