name: start-cluster
on: [push]
# on:
#   schedule:
#     - cron: '0 6 * * 1-5'

permissions:
  id-token: write
  contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: operations
    steps:
    - uses: actions/checkout@v2 #Clone Repo
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Install JQ
      run: sudo apt-get install -y jq
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
    - name: Running script
      run: TASK=start .github/workflows/scripts/dailytasks.sh
