name: sjohn-test
on:
  workflow_dispatch:
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'scripts'
          # sparse-checkout-cone-mode: false
          # token: ${{ github.token}}
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Test1
        working-directory: .
        run: pwd
        shell: bash
      - name: Test2
        working-directory: .
        run: ls -laR
        shell: bash
      - name: Test3
        working-directory: .
        run: ls -la ./scripts
        shell: bash