name: sjohn-test
on:
  workflow_dispatch:
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  testrun:
    runs-on: ubuntu-latest
    env:
      PROD_ENV: "radix_zone_prod.env"
      C2_ENV: "radix_zone_c2.env"
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'scripts/radix-zone'
          # sparse-checkout-cone-mode: true
          # token: ${{ github.token}}
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: "ENV PROD"
      #   run: cat ./scripts/radix-zone/${{ env.PROD_ENV }} >> $GITHUB_ENV_PROD
      - name: cat
        working-directory: .
        run: source ./scripts/radix-zone/radix_zone_prod.env
        shell: bash
      - name: Print environment variable
        run: echo $AZ_RESOURCE_KEYVAULT
      #   working-directory: .
      #   run: ls -la ./scripts
      #   shell: bash
      # - name: Import environment variables from a file
      #   id: import-env
      #   shell: bash
      #   run: |
      #     while read line; do
      #       echo "$line" >> $GITHUB_ENV
      #     done < ./scripts/radix-zone/radix_zone_prod.env

      # - name: Print environment variable
      #   run: echo $AZ_RESOURCE_KEYVAULT

      # - name: Test1
      #   working-directory: .
      #   run: pwd
      #   shell: bash
      # - name: Test2
      #   working-directory: .
      #   run: ls -lR
      #   shell: bash
      # - name: Test3
      #   working-directory: .
      #   run: ls -la ./scripts
      #   shell: bash