name: Storage Accounts
on:
  workflow_dispatch:
    inputs:
      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
          - "s940"
          - "s941"
permissions:
  id-token: write
  contents: read


env:
  terraform_version: ~1.3.0
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  resource_group_name: ${{ inputs.subscription }}-tfstate
  storage_account_name: ${{ inputs.subscription }}radixinfra
  container_name: infrastructure
  path: storageaccounts
  key: terraform.tfstate

jobs:
  StorageAccounts:
    runs-on: ubuntu-latest
    environment: operations
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Init
        working-directory: ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts/lab
        run: |
          terraform init \
          -backend-config='container_name=${{ env.container_name }}' \
          -backend-config='key=${{ env.path }}/${{ env.key }}' \
          -backend-config='resource_group_name=${{ env.resource_group_name }}' \
          -backend-config='storage_account_name=${{ env.storage_account_name }}'
      # - name: List files in the repository ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts
      #   run: |
      #     ls ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts
      # - name: Where am I
      #   run: |
      #     pwd
      # - name: ls (here)
      #   run: |
      #     ls -lh
      - name: Terraform Validate
        working-directory: ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts/lab
        run: terraform validate
      - name: Terraform Plan
        working-directory: ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts/lab
        run: terraform plan -lock=false
      
      # - run: echo "🍏 This job's status is ${{ job.status }}."