name: Storage Accounts
on:
  workflow_dispatch:
    inputs:
      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
          - "s940"
          - "s941"
permissions:
  id-token: write
  contents: read

env:
  terraform_version: ~1.3.0


jobs:
  StorageAccounts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts
        run: |
          ls ./terraform/infrastructure/${{ inputs.subscription }}/storageaccounts
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ $terraform_version }}
      
      # - run: echo "🍏 This job's status is ${{ job.status }}."