name: Storage Accounts
on:
  workflow_dispatch:
    inputs:
      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
          - "s940"
          - "s941"
permissions:
  id-token: write
  contents: read


env:
  terraform_version: ~1.3.0
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  resource_group_name: ${{ inputs.subscription }}-tfstate
  storage_account_name: ${{ inputs.subscription }}radixinfra
  container_name: infrastructure
  path: storageaccounts
  key: terraform.tfstate

jobs:
  StorageAccounts:
      runs-on: ubuntu-latest
      environment: ${{ inputs.subscription }}
      steps:
      - name: 'Az login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get GitHub Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Add GitHub IP to StorageAccount
        run: |
          az storage account network-rule add --resource-group "${{ env.resource_group_name }}" --account-name "${{ env.storage_account_name }}" --ip-address ${{ steps.ip.outputs.ipv4 }}
      - name: Lets sleep for 30 seconds for FW rule to complete
        run: sleep 30s
        shell: bash
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Terraform Init
        working-directory: ./terraform/${{ env.container_name }}/${{ inputs.subscription }}/${{ env.path }}
        run: |
          terraform init \
          -backend-config='container_name=${{ env.container_name }}' \
          -backend-config='key=${{ env.path }}/${{ env.key }}' \
          -backend-config='resource_group_name=${{ env.resource_group_name }}' \
          -backend-config='storage_account_name=${{ env.storage_account_name }}'
      - name: Terraform Validate
        working-directory: ./terraform/${{ env.container_name }}/${{ inputs.subscription }}/${{ env.path }}
        run: terraform validate
      - name: Terraform Plan
        working-directory: ./terraform/${{ env.container_name }}/${{ inputs.subscription }}/${{ env.path }}
        run: terraform plan -lock=false
      - name: Revoke GitHub IP on StorageAccount
        run: |
          az storage account network-rule remove --resource-group "${{ env.resource_group_name }}" --account-name "${{ env.storage_account_name }}" --ip-address ${{ steps.ip.outputs.ipv4 }}
      
      # - run: echo "🍏 This job's status is ${{ job.status }}."